# Generated by Django 4.1.4 on 2022-12-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20, verbose_name='그룹')),
                ('title', models.CharField(max_length=250, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('region', models.CharField(max_length=20, verbose_name='장소')),
                ('photo', models.ImageField(upload_to='')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
