# Generated by Django 4.1.4 on 2022-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default=1, max_length=150, verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
