# Generated by Django 4.1.4 on 2022-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_views_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(default='', max_length=20, verbose_name='그룹'),
        ),
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.CharField(default='', max_length=20, verbose_name='장소'),
        ),
    ]
