# Generated by Django 4.1.4 on 2022-12-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_post_group_alter_post_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='계정을 삭제하는 대신 선택을 해제함'),
        ),
    ]
