# Generated by Django 3.2 on 2022-12-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_email_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('chatting_id', models.CharField(default='242b241224mTR7k718CNS32gPXTlu18RHGIFpRNg5lJenibaMmmLI7KKebSm', max_length=128)),
                ('members', models.ManyToManyField(to='account.User')),
            ],
        ),
    ]
