# Generated by Django 3.2 on 2022-12-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chatting_id',
            field=models.CharField(default='242b2412241R3gZLHP6g5EBNgp5IDRhmMkuzN2mReNZ5F8nBrTQYsRgVs3wK6', max_length=128, unique=True),
        ),
    ]
