# Generated by Django 3.2 on 2022-12-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_group_chatting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chatting_id',
            field=models.CharField(default='242b241224AD39hMT3esdGkly12tOPluwTUKmxRnH1FIHxNC2eSYkPnU5smuxr', max_length=128, unique=True),
        ),
    ]
