# Generated by Django 3.2 on 2023-01-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_group_chatting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='chatting_id',
        ),
        migrations.AddField(
            model_name='group',
            name='chattingid',
            field=models.CharField(default='242b2412242fadg5eWz0RTJSVc6A6zmOma3j6JxxDx47ruNctZ4eIiETHfXAW', max_length=128, unique=True),
        ),
    ]
